CodeQ:
  LinkChecker:
    # how many concurrent requests should the command controller perform
    # If set too high, you most DOS your server
    concurrency: 10
    notifications:
      enabled: false
    excludeUrls:
      - ~^https://www.linkedin.com/.*~
      - ~^https://www.facebook.com/sharer/sharer.php\?~
